### ISSUE TITLE
Page breaks three lines before the page ends

### ISSUE THREAD

**Issue by orahcio** [mfontanini/presenterm-export#6]
Hi, congrats for the beautiful project, I'm using the presenterm in some classes. I tried to export presentations pdf inside NixOS 24.05 (my laptop) and Ubuntu 22.04 (work laptop), with some tools:
- presenterm 0.7.0;
- presenterm-export 0.2.1;
- tmux 3.4.

The result was a pdf with page breaks three lines before the end of the slide. I could to report just after some test with another machine, because I could see the closed Issue #4 , and it is almost the same one.
![Captura de imagem_20240511_174850](https://github.com/mfontanini/presenterm-export/assets/574899/234e90f3-22b3-495c-87de-3b903842c506)

**Comment by mfontanini** [comment]
Sorry, I never got back to you. I'm using the same versions as you and it works for me. You are not trying to resize the terminal while the export is running, right? What terminal are you using?

**Comment by orahcio** [comment]
Hi, I could see just now your message. I am not trying to resize. My terminal is .konsole-wrappe (output from fastfetch), just  konsole of the KDE Plasma. I think I tried also with kitty.

**Comment by tailhook** [comment]
Same issue for me, using alacritty, kitty and xterm. But I'm running a VM with `TERM=linux` (and no other active tmux session)

What terminal do you use that works?

**Comment by tailhook** [comment]
By the way, I think asciinema's [avt](https://docs.rs/avt/) library should help achieving the same thing without running tmux and controlling it via keys. I.e. you can just send strings to avt's virtual terminal and dump current state of the screeen for feeding to `ascii2html`.

**Comment by mfontanini** [comment]
This unfortunately started happening to me too after I upgraded my distro, which is very strange considering the python libraries used by this tool didn't change. I spent a while trying to find the issue but I'm not sure what it is. From what I saw, it's at the last stage when converting HTML to PDF, somehow the PDF ends up having lines with a higher height than they should and they end up overflowing.

I had actually started implementing native PDF generation straight from presenterm but it turns out the PDF format is a PITA and that created all sorts of other problems.

I'll prioritize this issue this week and try to get somewhere.

**Comment by mfontanini** [comment]
Btw I do like the idea of using `avt`, I wasn't aware of it. I'll look into that when I figure out this page cutting thing as tmux is not the culprit of the issue.

**Comment by mfontanini** [comment]
Alright I think the issue is fixed. I'd appreciate if someone could give it a try but at least for me it finally works. See https://github.com/mfontanini/presenterm-export/pull/12

**Comment by orahcio** [comment]
Nice job, I could to compile from source and everything is ok! tmux 3.5a on kitty. Congrats for the great project.
